platform: linux

image_resource:
  type: docker-image
  source:
    repository: python
    tag: 3.6.9-alpine3.9

#What resources from the pipeline we want as input
inputs:
- name: ci-repo
- name: repo

#Run the script that exists in the resource we requested
run:
  path: ci-repo/sample-pipelines/task-and-script/scripts/hello.sh