platform: linux

#What image the task will run on
image_resource:
  type: docker-image
  source:
    repository: alpine  #Pulls from Docker Hub by default

#What to run after the image is pulled
run:
  path: echo
  args:
  - "Hello, World!"